apiVersion: steward.sap.com/v1alpha1
kind: PipelineRun
metadata:
  generateName: network-profile-internet-
spec:
  profiles:
    network: internet
  jenkinsFile:
    repoUrl: https://github.com/SAP-samples/stewardci-example-pipelines
    revision: main
    relativePath: success/Jenkinsfile
  logging:
    elasticsearch:
      runID: {"build": 1}
