apiVersion: steward.sap.com/v1alpha1
kind: PipelineRun
metadata:
  generateName: full
spec:
  args:
    GIT_URL: https://github.com/SAP-samples/stewardci-example-pipelines
    GIT_BRANCH: main
    FILE_TO_SHOW: gitscm/dummy.txt
  jenkinsFile:
    repoUrl: https://github.com/SAP-samples/stewardci-example-pipelines
    revision: main
    relativePath: gitscm/Jenkinsfile
  #secrets:
  #- secret-used-in-pipeline
  logging:
    elasticsearch:
      runID: {"build": 1}
