apiVersion: steward.sap.com/v1alpha1
kind: PipelineRun
metadata:
  generateName: image-
spec:
  jenkinsfileRunner:
    image: stewardci/stewardci-jenkinsfile-runner:TEST_201006_b4e6c67
    imagePullPolicy: Always
  jenkinsFile:
    repoUrl: https://github.com/SAP-samples/stewardci-example-pipelines
    revision: master
    relativePath: success/Jenkinsfile
  logging:
    elasticsearch:
      runID: {"build": 1}
