apiVersion: steward.sap.com/v1alpha1
kind: PipelineRun
metadata:
  generateName: wronggiturl-
spec:
  jenkinsFile:
    repoUrl: https://github.com/sap-production/wrong-repo
    revision: main
    relativePath: Jenkinsfile
  logging:
    elasticsearch:
      runID: {"build": 1}
