apiVersion: steward.sap.com/v1alpha1
kind: PipelineRun
metadata:
  generateName: details-
spec:
  jenkinsFile:
    repoUrl: https://github.com/SAP-samples/stewardci-example-pipelines
    revision: master
    relativePath: sleep/Jenkinsfile
  runDetails:
    jobName: jobName1
    sequenceNumber: 42
    cause: "my cause"
  logging:
    elasticsearch:
      runID: {"build": 42}
