apiVersion: steward.sap.com/v1alpha1
kind: PipelineRun
metadata:
  generateName: sleep
spec:
  args:
    SLEEP_FOR_SECONDS: "120"
  jenkinsFile:
    repoUrl: https://github.com/SAP-samples/stewardci-example-pipelines
    revision: master
    relativePath: sleep/Jenkinsfile
  logging:
    elasticsearch:
      runID: {"build": 1}
