apiVersion: steward.sap.com/v1alpha1
kind: PipelineRun
metadata:
  generateName: error-
spec:
  jenkinsFile:
    repoUrl: https://github.com/SAP-samples/stewardci-example-pipelines
    revision: master
    relativePath: error/Jenkinsfile
  logging:
    elasticsearch:
      runID: {"build": 1}
