# Pipeline clone secret
apiVersion: v1
kind: Secret
metadata:
  name: github-example
type: kubernetes.io/basic-auth
stringData:
  username: myUser
  password: myToken
---
# Jenkins credential secret - referenced in pipeline
apiVersion: v1
kind: Secret
metadata:
  name: pipeline-as-a-service-example
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "Github credentials for prow user"
type: kubernetes.io/basic-auth
stringData:
  username: myUser
  password: myToken
---
# Jenkins credential secret - referenced in pipeline
apiVersion: v1
kind: Secret
metadata:
  name: deploy-example
  labels:
    param: GIT_CREDENTIAL_ID
    "jenkins.io/credentials-type": "secretFile"
  annotations:
    "jenkins.io/credentials-description" : "Description here"
type: Opaque
stringData:
  filename: git-cred.json
data:
  data: base64encodedString=
