apiVersion: steward.sap.com/v1alpha1
kind: PipelineRun
metadata:
  generateName: rename-secret-
spec:
  jenkinsFile:
    repoUrl: https://github.com/SAP-samples/stewardci-example-pipelines
    revision: master
    relativePath: secret/Jenkinsfile
  args: 
    SECRETID: renamed
    EXPECTEDUSER: foo
    EXPECTEDPWD: abc123
  secrets:
  - secret
  logging:
    elasticsearch:
      runID: {"build": 1}
