apiVersion: steward.sap.com/v1alpha1
kind: PipelineRun
metadata:
  generateName: missingsecret-
spec:
  jenkinsFile:
    repoUrl: https://github.com/SAP-samples/stewardci-example-pipelines
    revision: main
    relativePath: success/Jenkinsfile
  secrets:
  - unknown
  logging:
    elasticsearch:
      runID: {"build": 1}
