apiVersion: v1
kind: Secret
metadata:
  name: secret
  annotations:
    steward.sap.com/secret-rename-to: renamed
  labels:
    jenkins.io/credentials-type: usernamePassword 
type: kubernetes.io/basic-auth
stringData:
  username: foo
  password: abc123
