apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: steward-run-controller-metrics 
  namespace: steward-system 
spec:
  selector:
    matchLabels:
      app: steward-run-controller
  endpoints:
  - port:  http-metrics

