{{/* vim: set filetype=mustache: */}}
{{/*
Expand the name of the chart.
*/}}
{{- define "steward.name" -}}
{{- .Chart.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "steward.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Common labels
*/}}
{{- define "steward.labels" -}}
helm.sh/chart: {{ include "steward.chart" . }}
{{ include "steward.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
{{- end -}}

{{/*
Selector labels
*/}}
{{- define "steward.selectorLabels" -}}
app.kubernetes.io/name: {{ include "steward.name" . | quote }}
{{- end -}}

{{/*
The component label for the run controller.
*/}}
{{- define "steward.runController.componentLabel" -}}
app.kubernetes.io/component: run-controller
{{- end -}}

{{/*
The component label for the tenant controller.
*/}}
{{- define "steward.tenantController.componentLabel" -}}
app.kubernetes.io/component: tenant-controller
{{- end -}}

{{/*
The additional labels for the service monitors.
*/}}
{{- define "steward.serviceMonitors.extraLabels" -}}
{{- if .Values.metrics.serviceMonitors.extraLabels -}}
{{- toYaml .Values.metrics.serviceMonitors.extraLabels -}}
{{- end -}}
{{- end -}}

{{/*
podSecurityPolicyName for the run controller
*/}}
{{- define "steward.runController.podSecurityPolicyName" -}}
{{- if .Values.runController.podSecurityPolicyName -}}
{{- .Values.runController.podSecurityPolicyName | quote -}}
{{- else -}}
{{- printf "00-steward-controllers" -}}
{{- end -}}
{{- end -}}

{{/*
podSecurityPolicyName for the tenant controller
*/}}
{{- define "steward.tenantController.podSecurityPolicyName" -}}
{{- if .Values.tenantController.podSecurityPolicyName -}}
{{- .Values.tenantController.podSecurityPolicyName | quote -}}
{{- else -}}
{{- printf "00-steward-controllers" -}}
{{- end -}}
{{- end -}}

{{/*
podSecurityPolicyName for pipelineRuns
*/}}
{{- define "steward.pipelineRuns.podSecurityPolicyName" -}}
{{- if .Values.pipelineRuns.podSecurityPolicyName -}}
{{- .Values.pipelineRuns.podSecurityPolicyName | quote -}}
{{- else -}}
{{- printf "00-steward-run" -}}
{{- end -}}
{{- end -}}

{{/*
template for the controllers to decide if PDP should be generated
or will be generated by the consumer of this helmchart.
*/}}
{{- define "steward.controllers.generatePodSecurityPolicy" -}}
{{- if or (eq (include "steward.runController.podSecurityPolicyName" .) "00-steward-controllers") (eq (include "steward.tenantController.podSecurityPolicyName" .) "00-steward-controllers") -}}
{{- printf "true" -}}
{{- else -}}
{{- printf "" -}}
{{- end -}}
{{- end -}}

{{/*
template for pipelineRuns to decide if PDP should be generated
or will be generated by the consumer of this helmchart.
*/}}
{{- define "steward.pipelineRuns.generatePodSecurityPolicy" -}}
{{ if eq (include "steward.pipelineRuns.podSecurityPolicyName" .) "00-steward-run" }}
{{- printf "true" -}}
{{- else -}}
{{- printf "" -}}
{{- end -}}
{{- end -}}
