kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: steward-tenant
  labels:
    {{- include "steward.labels" . | nindent 4 }}
rules:
- apiGroups: ["steward.sap.com"]
  resources: ["pipelineruns"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create","delete","get","list","patch","update","watch"]
