apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: 00-steward-controllers
  labels:
    {{- include "steward.labels" . | nindent 4 }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  {{- .Values.podSecurityPolicy.controllers | default ( $.Files.Get "data/controllers-default-podsecuritypolicy.yaml" ) | nindent 2 }}
