{{- if .Values.tenantController.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: steward-tenant-controller
  namespace: {{ .Values.targetNamespace.name | quote }}
  labels:
    {{- include "steward.labels" . | nindent 4 }}
{{- end }}