{{- if .Values.metrics.serviceMonitors.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: steward-tenant-controller-metrics 
  namespace: steward-system 
spec:
  selector:
    matchLabels:
      app:  {{- include "steward.tenant-controller.componentLabel" .}}
  endpoints:
  - port:  http-metrics
{{- end }}
