apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: steward-jenkinsfile-runner
  namespace: {{ .Values.targetNamespace.name | quote }}
  labels:
    {{- include "steward.labels" . | nindent 4 }}
    {{- include "steward.runController.componentLabel" . | nindent 4 }}
spec:
  params:
  - name: PIPELINE_PARAMS_JSON
    type: string
    description: >
      Parameters to pass to the pipeline, as JSON string.
  - name: PIPELINE_GIT_URL
    type: string
    description: >
      The URL of the Git repository containing the pipeline definition.
  - name: PIPELINE_GIT_REVISION
    type: string
    description: >
      The revision of the pipeline Git repository to used, e.g. 'master'.
  - name: PIPELINE_FILE
    type: string
    description: >
      The relative pathname of the pipeline definition file, typically 'Jenkinsfile'.
  - name: PIPELINE_LOG_ELASTICSEARCH_INDEX_URL
    type: string
    description: >
      The URL of the Elasticsearch index to send logs to.
      If null or empty, logging to Elasticsearch is disabled.
      # Example: http://elasticsearch-primary.elasticsearch.svc.cluster.local:9200/jenkins-logs/_doc
    default: {{ default "" .Values.pipelineRuns.logging.elasticsearch.indexURL | quote }}
  - name: PIPELINE_LOG_ELASTICSEARCH_AUTH_SECRET
    type: string
    description: >
      The name of the secret of type basic-auth to use to authenticate to Elasticsearch.
      If null or empty, no authentication takes place.
    default: ""
  - name: PIPELINE_LOG_ELASTICSEARCH_TRUSTEDCERTS_SECRET
    type: string
    description: >
      The name of the secret providing the trusted certificates bundle used for TLS server verification when connecting to Elasticsearch.
      If null or empty, the default trusted certificates are used.
    default: ""
  - name: PIPELINE_LOG_ELASTICSEARCH_RUN_ID_JSON
    type: string
    description: >
      The value for the 'runId' field of log events, as JSON string.
      Must be specified if logging to Elasticsearch is enabled.
    default: ""
  - name: RUN_NAMESPACE
    type: string
    description: >
      The namespace of this pipeline run.
  - name: JOB_NAME
    type: string
    description: >
      The name of the job this pipeline run belongs to. It is used as the name of the Jenkins job and therefore must be a valid Jenkins job name.
      If null or empty, `job` will be used.
    default: ""
  - name: RUN_NUMBER
    type: string
    description: >
      The sequence number of the pipeline run, which translates into the build number of the Jenkins job.
      If null or empty, `1` is used.
    default: "1"
  - name: RUN_CAUSE
    type: string
    description: >
      A textual description of the cause of this pipeline run. Will be set as cause of the Jenkins job.
      If null or empty, no cause information will be available.
    default: ""
  - name: JFR_IMAGE
    type: string
    description: >
      The Jenkinsfile Runner image to be used.
  - name: JFR_IMAGE_PULL_POLICY
    type: string
    default: "IfNotPresent"
    description: >
      The image pull policy for JFR_IMAGE. Defaults to 'IfNotPresent'.
  steps:
  - name: jenkinsfile-runner
    image: $(params.JFR_IMAGE)
    imagePullPolicy: $(params.JFR_IMAGE_PULL_POLICY)
    # Workaround for Tekton being affected by registry rate limiting.
    # Specifying the command here prevents Tekton from downloading the image
    # manifest from the registry to obtain the entrypoint command from there.
    command: ["/steward-interface/entrypoint"]
    env:
    - name: XDG_CONFIG_HOME
      value: /home/jenkins
    - name: JAVA_OPTS
      value: {{ default "" .Values.pipelineRuns.jenkinsfileRunner.javaOpts | squote }}
    - name: PIPELINE_GIT_URL
      value: '$(params.PIPELINE_GIT_URL)'
    - name: PIPELINE_GIT_REVISION
      value: '$(params.PIPELINE_GIT_REVISION)'
    - name: PIPELINE_FILE
      value: '$(params.PIPELINE_FILE)'
    - name: PIPELINE_PARAMS_JSON
      value: '$(params.PIPELINE_PARAMS_JSON)'
    - name: PIPELINE_LOG_ELASTICSEARCH_INDEX_URL
      value: '$(params.PIPELINE_LOG_ELASTICSEARCH_INDEX_URL)'
    - name: PIPELINE_LOG_ELASTICSEARCH_AUTH_SECRET
      value: '$(params.PIPELINE_LOG_ELASTICSEARCH_AUTH_SECRET)'
    - name: PIPELINE_LOG_ELASTICSEARCH_TRUSTEDCERTS_SECRET
      value: '$(params.PIPELINE_LOG_ELASTICSEARCH_TRUSTEDCERTS_SECRET)'
    - name: PIPELINE_LOG_ELASTICSEARCH_RUN_ID_JSON
      value: '$(params.PIPELINE_LOG_ELASTICSEARCH_RUN_ID_JSON)'
    - name: PIPELINE_CLONE_RETRY_INTERVAL_SEC
      value: {{ default "" .Values.pipelineRuns.jenkinsfileRunner.pipelineCloneRetryIntervalSec | squote }}
    - name: PIPELINE_CLONE_RETRY_TIMEOUT_SEC
      value: {{ default "" .Values.pipelineRuns.jenkinsfileRunner.pipelineCloneRetryTimeoutSec | squote }}
    - name: RUN_NAMESPACE
      value: '$(params.RUN_NAMESPACE)'
    - name: JOB_NAME
      value: '$(params.JOB_NAME)'
    - name: RUN_NUMBER
      value: '$(params.RUN_NUMBER)'
    - name: RUN_CAUSE
      value: '$(params.RUN_CAUSE)'
    - name: TERMINATION_LOG_PATH
      value: /tekton/results/jfr-termination-log
    {{- with .Values.pipelineRuns.logging.forwarding }}{{- if .enabled }}
    - name: PIPELINE_LOG_FLUENTD_HOST
      {{- if .useSidecar }}
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
      {{- else }}
      value: {{ required "the host name of the log-forwarder" .host  }}
      {{- end }}
    - name: PIPELINE_LOG_FLUENTD_PORT
      value: {{ .port | quote }}
    - name: PIPELINE_LOG_FLUENTD_TAG
      value: {{ .tag }}
    - name: PIPELINE_LOGS_PLUGIN_SENDER_BASE_RETRY_INTERVAL_MILLIS
      value: {{ required "the senderBaseRetryIntervalMillis parameter in the 'elasticsearch-logs-plugin'" .senderBaseRetryIntervalMillis | quote }}
    - name: PIPELINE_LOGS_PLUGIN_SENDER_MAX_RETRY_INTERVAL_MILLIS
      value: {{ required "the senderMaxRetryIntervalMillis parameter in the 'elasticsearch-logs-plugin'" .senderMaxRetryIntervalMillis | quote }}
    - name: PIPELINE_LOGS_PLUGIN_SENDER_MAX_RETRY_COUNT
      value: {{ required "the senderMaxRetryCount parameter in the 'elasticsearch-logs-plugin'" .senderMaxRetryCount | quote }}
    - name: PIPELINE_LOGS_PLUGIN_CONNECTION_TIMEOUT_MILLIS
      value: {{ required "the connectionTimeoutMillis parameter in the 'elasticsearch-logs-plugin'" .connectionTimeoutMillis | quote }}
    - name: PIPELINE_LOGS_PLUGIN_READ_TIMEOUT_MILLIS
      value: {{ required "the readTimeoutMillis parameter in the 'elasticsearch-logs-plugin'" .readTimeoutMillis | quote }}
    {{- if .splitMessagesLongerThan }}
    - name: PIPELINE_LOGS_PLUGIN_SPLIT_MESSAGES_LONGER_THAN
      value: {{ .splitMessagesLongerThan | quote }}
    {{- end }}
    {{- if .bufferChunkInitialSize }}
    - name: PIPELINE_LOGS_PLUGIN_BUFFER_CHUNK_INITIAL_SIZE
      value: {{ .bufferChunkInitialSize | quote }}
    {{- end }}
    {{- if .bufferChunkRetentionSize }}
    - name: PIPELINE_LOGS_PLUGIN_BUFFER_CHUNK_RETENTION_SIZE
      value: {{ .bufferChunkRetentionSize | quote }}
    {{- end }}
    {{- if .maxBufferSize }}
    - name: PIPELINE_LOGS_PLUGIN_MAX_BUFFER_SIZE
      value: {{ .maxBufferSize | quote }}
    {{- end }}
    {{- if .bufferChunkRetentionTimeMillis }}
    - name: PIPELINE_LOGS_PLUGIN_BUFFER_CHUNK_RETENTION_TIME_MILLIS
      value: {{ .bufferChunkRetentionTimeMillis | quote }}
    {{- end }}
    {{- if .maxWaitSecondsUntilBufferFlushed }}
    - name: PIPELINE_LOGS_PLUGIN_MAX_WAIT_SECONDS_UNTIL_BUFFER_FLUSHED
      value: {{ .maxWaitSecondsUntilBufferFlushed | quote }}
    {{- end }}
    {{- if .maxWaitSecondsUntilFlusherTerminated }}
    - name: PIPELINE_LOGS_PLUGIN_MAX_WAIT_SECONDS_UNTIL_FLUSHER_TERMINATED
      value: {{ .maxWaitSecondsUntilFlusherTerminated | quote }}
    {{- end }}
    {{- if .flushAttemptIntervalMillis }}
    - name: PIPELINE_LOGS_PLUGIN_FLUSH_ATTEMPT_INTERVAL_MILLIS
      value: {{ .flushAttemptIntervalMillis | quote }}
    {{- end }}
    {{- if .emitMaxRetriesIfBufferFull }}
    - name: PIPELINE_LOGS_PLUGIN_EMIT_MAX_RETRIES_IF_BUFFER_FULL
      value: {{ .emitMaxRetriesIfBufferFull | quote }}
    {{- end }}
    {{- end }}{{- end}}
    resources:
      {{- toYaml .Values.pipelineRuns.jenkinsfileRunner.resources | nindent 6 }}
    terminationMessagePath: /tekton/results/jfr-termination-log
  results:
  - name: jfr-termination-log
    description: The termination log message from the Jenkinsfile Runner
  {{ with .Values.pipelineRuns.sidecars }}
  sidecars:
    {{ toYaml . | nindent 4 }}
  {{ end }}

