apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: steward-jenkinsfile-runner
  namespace: {{ .Values.targetNamespace.name | quote }}
  labels:
    {{- include "steward.labels" . | nindent 4 }}
    {{- include "steward.runController.componentLabel" . | nindent 4 }}
spec:
  params:
  - name: PIPELINE_PARAMS_JSON
    type: string
    description: >
      Parameters to pass to the pipeline, as JSON string.
  - name: PIPELINE_GIT_URL
    type: string
    description: >
      The URL of the Git repository containing the pipeline definition.
  - name: PIPELINE_GIT_REVISION
    type: string
    description: >
      The revision of the pipeline Git repository to used, e.g. 'master'.
  - name: PIPELINE_FILE
    type: string
    description: >
      The relative pathname of the pipeline definition file, typically 'Jenkinsfile'.
  - name: PIPELINE_LOG_ELASTICSEARCH_INDEX_URL
    type: string
    description: >
      The URL of the Elasticsearch index to send logs to.
      If null or empty, logging to Elasticsearch is disabled.
      # Example: http://elasticsearch-primary.elasticsearch.svc.cluster.local:9200/jenkins-logs/_doc
    default: {{ default "" .Values.pipelineRuns.logging.elasticsearch.indexURL | quote }}
  - name: PIPELINE_LOG_ELASTICSEARCH_AUTH_SECRET
    type: string
    description: >
      The name of the secret of type basic-auth to use to authenticate to Elasticsearch.
      If null or empty, no authentication takes place.
    default: ""
  - name: PIPELINE_LOG_ELASTICSEARCH_TRUSTEDCERTS_SECRET
    type: string
    description: >
      The name of the secret providing the trusted certificates bundle used for TLS server verification when connecting to Elasticsearch.
      If null or empty, the default trusted certificates are used.
    default: ""
  - name: PIPELINE_LOG_ELASTICSEARCH_RUN_ID_JSON
    type: string
    description: >
      The value for the 'runId' field of log events, as JSON string.
      Must be specified if logging to Elasticsearch is enabled.
    default: ""
  - name: RUN_NAMESPACE
    type: string
    description: >
      The namespace of this pipeline run.
  - name: JOB_NAME
    type: string
    description: >
      The name of the job this pipeline run belongs to. It is used as the name of the Jenkins job and therefore must be a valid Jenkins job name.
      If null or empty, `job` will be used.
    default: ""
  - name: RUN_NUMBER
    type: string
    description: >
      The sequence number of the pipeline run, which translates into the build number of the Jenkins job.
      If null or empty, `1` is used.
    default: "1"
  - name: RUN_CAUSE
    type: string
    description: >
      A textual description of the cause of this pipeline run. Will be set as cause of the Jenkins job.
      If null or empty, no cause information will be available.
    default: ""
  - name: JFR_IMAGE
    type: string
    description: >
      The Jenkinsfile Runner image to be used.
  - name: JFR_IMAGE_PULL_POLICY
    type: string
    default: "IfNotPresent"
    description: >
      The image pull policy for JFR_IMAGE. Defaults to 'IfNotPresent'.
  steps:
  - name: jenkinsfile-runner
    image: $(params.JFR_IMAGE)
    imagePullPolicy: $(params.JFR_IMAGE_PULL_POLICY)
    # Workaround for Tekton being affected by registry rate limiting.
    # Specifying the command here prevents Tekton from downloading the image
    # manifest from the registry to obtain the entrypoint command from there.
    command: ["/steward-interface/entrypoint"]
    env:
    - name: XDG_CONFIG_HOME
      value: /home/jenkins
    - name: JAVA_OPTS
      value: {{ default "" .Values.pipelineRuns.jenkinsfileRunner.javaOpts | squote }}
    - name: PIPELINE_GIT_URL
      value: '$(params.PIPELINE_GIT_URL)'
    - name: PIPELINE_GIT_REVISION
      value: '$(params.PIPELINE_GIT_REVISION)'
    - name: PIPELINE_FILE
      value: '$(params.PIPELINE_FILE)'
    - name: PIPELINE_PARAMS_JSON
      value: '$(params.PIPELINE_PARAMS_JSON)'

    # log streaming
    - name: PIPELINE_LOG_ELASTICSEARCH_INDEX_URL
      value: '$(params.PIPELINE_LOG_ELASTICSEARCH_INDEX_URL)'
    - name: PIPELINE_LOG_ELASTICSEARCH_AUTH_SECRET
      value: '$(params.PIPELINE_LOG_ELASTICSEARCH_AUTH_SECRET)'
    - name: PIPELINE_LOG_ELASTICSEARCH_TRUSTEDCERTS_SECRET
      value: '$(params.PIPELINE_LOG_ELASTICSEARCH_TRUSTEDCERTS_SECRET)'
    - name: PIPELINE_LOG_ELASTICSEARCH_RUN_ID_JSON
      value: '$(params.PIPELINE_LOG_ELASTICSEARCH_RUN_ID_JSON)'
    {{- with .Values.pipelineRuns.logging.elasticsearch }}
    {{- with .connectTimeoutMillis }}
    - name: PIPELINE_LOG_ELASTICSEARCH_CONNECT_TIMEOUT_MILLIS
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .requestTimeoutMillis }}
    - name: PIPELINE_LOG_ELASTICSEARCH_REQUEST_TIMEOUT_MILLIS
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .socketTimeoutMillis }}
    - name: PIPELINE_LOG_ELASTICSEARCH_SOCKET_TIMEOUT_MILLIS
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .splitMessagesLongerThan }}
    - name: PIPELINE_LOG_ELASTICSEARCH_SPLIT_MESSAGES_LONGER_THAN
      value: {{ . | int | squote }}
    {{- end }}
    {{- end }}
    {{- with .Values.pipelineRuns.logging.forwarder }}
    {{- if .enabled }}
    - name: PIPELINE_LOG_FLUENTD_HOST
      {{- if .useSidecar }}
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
      {{- else }}
      value: {{ required "value 'pipelineRuns.logging.forwarder.host' must be set" .host | squote }}
      {{- end }}
    - name: PIPELINE_LOG_FLUENTD_PORT
      value: {{ required "value 'pipelineRuns.logging.forwarder.port' must be set" .port | int | squote }}
    - name: PIPELINE_LOG_FLUENTD_TAG
      value: {{ required "value 'pipelineRuns.logging.forwarder.tag' must be set" .tag | squote }}
    {{- with .senderBaseRetryIntervalMillis }}
    - name: PIPELINE_LOG_FLUENTD_SENDER_BASE_RETRY_INTERVAL_MILLIS
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .senderMaxRetryIntervalMillis }}
    - name: PIPELINE_LOG_FLUENTD_SENDER_MAX_RETRY_INTERVAL_MILLIS
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .senderMaxRetryCount }}
    - name: PIPELINE_LOG_FLUENTD_SENDER_MAX_RETRY_COUNT
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .connectionTimeoutMillis }}
    - name: PIPELINE_LOG_FLUENTD_CONNECTION_TIMEOUT_MILLIS
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .readTimeoutMillis }}
    - name: PIPELINE_LOG_FLUENTD_READ_TIMEOUT_MILLIS
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .maxWaitSecondsUntilBufferFlushed }}
    - name: PIPELINE_LOG_FLUENTD_MAX_WAIT_SECONDS_UNTIL_BUFFER_FLUSHED
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .maxWaitSecondsUntilFlusherTerminated }}
    - name: PIPELINE_LOG_FLUENTD_MAX_WAIT_SECONDS_UNTIL_FLUSHER_TERMINATED
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .bufferChunkInitialSize }}
    - name: PIPELINE_LOG_FLUENTD_BUFFER_CHUNK_INITIAL_SIZE
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .bufferChunkRetentionSize }}
    - name: PIPELINE_LOG_FLUENTD_BUFFER_CHUNK_RETENTION_SIZE
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .bufferChunkRetentionTimeMillis }}
    - name: PIPELINE_LOG_FLUENTD_BUFFER_CHUNK_RETENTION_TIME_MILLIS
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .flushAttemptIntervalMillis }}
    - name: PIPELINE_LOG_FLUENTD_FLUSH_ATTEMPT_INTERVAL_MILLIS
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .maxBufferSize }}
    - name: PIPELINE_LOG_FLUENTD_MAX_BUFFER_SIZE
      value: {{ . | int | squote }}
    {{- end }}
    {{- with .emitTimeoutMillis }}
    - name: PIPELINE_LOG_FLUENTD_EMIT_TIMEOUT_MILLIS
      value: {{ . | int | squote }}
    {{- end }}
    {{- end }}
    {{- end }}

    - name: PIPELINE_CLONE_RETRY_INTERVAL_SEC
      value: {{ default "" .Values.pipelineRuns.jenkinsfileRunner.pipelineCloneRetryIntervalSec | squote }}
    - name: PIPELINE_CLONE_RETRY_TIMEOUT_SEC
      value: {{ default "" .Values.pipelineRuns.jenkinsfileRunner.pipelineCloneRetryTimeoutSec | squote }}
    - name: RUN_NAMESPACE
      value: '$(params.RUN_NAMESPACE)'
    - name: JOB_NAME
      value: '$(params.JOB_NAME)'
    - name: RUN_NUMBER
      value: '$(params.RUN_NUMBER)'
    - name: RUN_CAUSE
      value: '$(params.RUN_CAUSE)'
    - name: TERMINATION_LOG_PATH
      value: /tekton/results/jfr-termination-log
    resources:
      {{- toYaml .Values.pipelineRuns.jenkinsfileRunner.resources | nindent 6 }}
    terminationMessagePath: /tekton/results/jfr-termination-log
  results:
  - name: jfr-termination-log
    description: The termination log message from the Jenkinsfile Runner
  {{ with .Values.pipelineRuns.jenkinsfileRunner.sidecars }}
  sidecars:
    {{ toYaml . | nindent 4 }}
  {{ end }}
