apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tenants.steward.sap.com
spec:
  group: steward.sap.com
  version: v1alpha1
  names:
    kind: Tenant
    singular: tenant
    plural: tenants
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
    - name: Progress
      type: string
      description: The current progress of tenant preparation
      JSONPath: .status.progress
      priority: 1
    - name: Result
      type: string
      description: The current result of tenant preparation
      JSONPath: .status.result
      priority: 0
    - name: Tenant-Namespace
      type: string
      description: The name of the namespace for this tenant
      JSONPath: .status.tenantNamespaceName
      priority: 0
  validation:
    openAPIV3Schema:
      type: object
      required:
        - spec
      properties:
        spec: ###
          type: object
          required: #TODO: Really required? Compare with tenant_types.go
            - name
            - displayName
          properties:
            name: ###
              type: string
              pattern: '^[^\s]{1,}.*$'
            displayName: ###
              type: string
              pattern: '^[^\s]{1,}.*$'
