{
 "title": "Steward",
 "time": { "from": "2021-07-24T01:23:22.756Z", "to": "2021-07-28T22:18:13.606Z" },
 "panels": [
  {
   "title": "Totals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "pipelines" }
   ],
   "targets": [
    {
     "expr": "sum(steward_pipelineruns_started_total)-sum(steward_pipelineruns_completed_total)",
     "legendFormat": "running pipelines"
    },
    { "expr": "sum(steward_tenants_total)", "legendFormat": "tenants" }
   ]
  },
  {
   "title": "Pipeline Runs (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(steward_pipelineruns_started_total[1m])",
     "legendFormat": "started"
    },
    {
     "expr": "increase(steward_pipelineruns_completed_total[1m])",
     "legendFormat": "finished_{{result}}"
    }
   ]
  },
  {
   "title": "Durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s", "label": "duration" }
   ],
   "targets": [
    {
     "expr": "rate(steward_pipelineruns_state_duration_seconds_sum[1m])/rate(steward_pipelineruns_state_duration_seconds_count[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Quantiles Pipeline Run Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(steward_pipelineruns_state_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.8,sum(rate(steward_pipelineruns_state_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "80%"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(steward_pipelineruns_state_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(steward_pipelineruns_state_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Observation Of Ongoing Pipeline Runs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }
  },
  {
   "title": "Duration of Pipeline Runs in State 'new'",
   "type": "heatmap",
   "description": "Heatmap pipeline runs duration's in state new. Due the periodic observations of pipeline runs in certain intervals it's possible that some are not counted at all and some are counted multiple times, so that the absolute values are only an approximation.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (le)(increase(steward_pipelineruns_ongoing_state_duration_periodic_observations_seconds_bucket{state=\"new\"}[1m])) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Duration of Pipeline Runs in State 'preparing'",
   "type": "heatmap",
   "description": "Heatmap pipeline runs duration's in state preparing. Due the periodic observations of pipeline runs in certain intervals it's possible that some are not counted at all and some are counted multiple times, so that the absolute values are only an approximation.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by (le)(increase(steward_pipelineruns_ongoing_state_duration_periodic_observations_seconds_bucket{state=\"preparing\"}[1m])) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Duration of Pipeline Runs in State 'waiting'",
   "type": "heatmap",
   "description": "Heatmap pipeline runs duration's in state waiting. Due the periodic observations of pipeline runs in certain intervals it's possible that some are not counted at all and some are counted multiple times, so that the absolute values are only an approximation.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by (le)(increase(steward_pipelineruns_ongoing_state_duration_periodic_observations_seconds_bucket{state=\"waiting\"}[1m])) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Duration of Pipeline Runs in State 'cleaning'",
   "type": "heatmap",
   "description": "Heatmap pipeline runs duration's in state cleaning. Due the periodic observations of pipeline runs in certain intervals it's possible that some are not counted at all and some are counted multiple times, so that the absolute values are only an approximation.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum by (le)(increase(steward_pipelineruns_ongoing_state_duration_periodic_observations_seconds_bucket{state=\"cleaning\"}[1m])) ",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}