{
 "title": "Steward",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Totals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "pipelines" }
   ],
   "targets": [
    {
     "expr": "sum(steward_pipeline_runs_started_total_count)-sum(steward_pipeline_runs_completed_total_count)",
     "legendFormat": "running pipelines"
    },
    {
     "expr": "sum(steward_tenant_total_number)",
     "legendFormat": "tenants"
    }
   ]
  },
  {
   "title": "Pipeline Runs (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(steward_pipeline_runs_started_total_count[1m])",
     "legendFormat": "started"
    },
    {
     "expr": "increase(steward_pipeline_runs_completed_total_count[1m])",
     "legendFormat": "finished_{{result}}"
    }
   ]
  },
  {
   "title": "Durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "rate(steward_pipeline_run_duration_seconds_sum[1m])/rate(steward_pipeline_run_duration_seconds_count[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Quantiles Pipeline Run Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(steward_pipeline_run_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.8,sum(rate(steward_pipeline_run_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "80%"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(steward_pipeline_run_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(steward_pipeline_run_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "99%"
    }
   ]
  }
 ]
}