kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: steward-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create","delete","get","list","patch","update","watch"]
