/*
#########################
#  SAP Steward-CI       #
#########################

THIS CODE IS GENERATED! DO NOT TOUCH!

Copyright SAP SE.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/SAP/stewardci-core/pkg/apis/steward/v1alpha1"
)

// ElasticsearchApplyConfiguration represents an declarative configuration of the Elasticsearch type for use
// with apply.
type ElasticsearchApplyConfiguration struct {
	RunID      *v1alpha1.CustomJSON `json:"runID,omitempty"`
	IndexURL   *string              `json:"indexURL,omitempty"`
	AuthSecret *string              `json:"authSecret,omitempty"`
}

// ElasticsearchApplyConfiguration constructs an declarative configuration of the Elasticsearch type for use with
// apply.
func Elasticsearch() *ElasticsearchApplyConfiguration {
	return &ElasticsearchApplyConfiguration{}
}

// WithRunID sets the RunID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RunID field is set to the value of the last call.
func (b *ElasticsearchApplyConfiguration) WithRunID(value v1alpha1.CustomJSON) *ElasticsearchApplyConfiguration {
	b.RunID = &value
	return b
}

// WithIndexURL sets the IndexURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IndexURL field is set to the value of the last call.
func (b *ElasticsearchApplyConfiguration) WithIndexURL(value string) *ElasticsearchApplyConfiguration {
	b.IndexURL = &value
	return b
}

// WithAuthSecret sets the AuthSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthSecret field is set to the value of the last call.
func (b *ElasticsearchApplyConfiguration) WithAuthSecret(value string) *ElasticsearchApplyConfiguration {
	b.AuthSecret = &value
	return b
}
